# Site settings
title: Jing Chen's CV 
description: cj2jion's CV
favicon: /assets/img/avatar.JPG
baseurl: https://cj2jion.github.io
url: https://cj2jion.github.io
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Jing Chen
  telephone: (+86) 182-0012-9094
  address: Chengdu, Sichuan
  email: ccjing93@gmail.com
  link: http://cj2jion.com
  weibo: jion-jing
  github: cj2jion
  linkedin: jing-chen-03b60811a
  facebook: Jing Chen
  gavatar: /cj2jion.github.io/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  educationHistory:
    - education1:
      organization: University of Electronic Science and Technology of China(UESTC)
      location: Chengdu,Sichuan, China
      degree: Bachelor
      major: Networking Engineering
      started: 2013
      duration: (2013 - 2017)
      honor1: Honorable Mention of Interdisciplinary Contest In Modeling
      honor2: Third-class prize of The Chinese Mathematics Competitions(CMC)
      description: Top 5% in faculty, GPA:3.8/4.0, CET-4:539, CET-6:454 . National Endeavor Fellowship  awarded in Dec 2015 . Third-class People's Scholarship awarded in Dec 2014 .
    - education2:
      organization: Mitacs Globalink Research Internship & Carleton University
      location: Ottawa, ON, Canada
      degree: Intern
      major: School of Mathematics and Statistics
      started: 2016
      duration: (2016.5 - 2016.8)
     
  workHistory:
    - work1:
      company: Design and Implementation of Access Control System
      location: Chengdu, Sichuan
      title: instructor：Iixiang Ma
      started: 2016
      duration: (2016 . 2 - 2016 . 5 )
      description: Successfully completed the design and structures of PPPoE - RADIUS access control system. And through the configuration and debugging, completed the remote authentication. Results shown that through self-built access control system to realize the access control of multiple users.  https://github.com/cj2jion/Access-Control-System
    - work2: 
      company: C + + implement the problem of recording multiple the shortest paths 
      location: Chengdu, Sichuan
      title: Personal projects
      started: 2016
      duration: (2016 . 2 - 2016 . 5 )
      description: Make up for the void that traditional Dijkstra algorithm can record only one of the shortest path which from monophyletic to other each node.Realized recording multiple front adjacency nodes and multiple the shortest paths which from monophyletic to other nodes.
    - work3:
      company: Interdisciplinary Contest In Modeling of USA in 2015
      location: Chengdu, Sichuan
      title: team leader，paper writing in English
      started: 2015
      duration: (2015 . 2 - 2015 . 4 )
      description: Develop a model for the sustainability of a country, provided a measure to  clearly defined when and how a county is sustainable or unsustainable.
    - work4:
      company: Simulation on Principle of Communication Protocol and Routing Algorithm
      location: Chengdu, Sichuan
      title: Team member
      started: 2015
      duration: (2015 . 3 - 2015 . 7)
      description: Designed communication protocol, realized the function of information and text transmission with communication simulation software--comexpm.exe. Initialized, diffused routing information and calculated routing by method of distance vector and link state routing algorithm with route selection algorithm simulation software--routing.exe.  
    - work5:
      company: Instant Messaging Software for LAN
      location: Chengdu, Sichuan
      title: team leader，c++
      started: 2014
      duration: (2014 . 12 - 2015 . 5 )
      description: Created a instant messaging software for LAN, through it, people in LAN can contact and transfer files without connected to Internet. This research mainly studies the communication in LAN in the TCP/IP protocol, which uses the Client / Server (C/S) mode and TCP connection 
    - work6:
      company: SAMSUNG Charity and “Bee' Home” Public Service Team
      location: Ya'an, Sichuan
      title: Team member
      started: 2014
      duration: (summer 2014)
      description: Taught the Children the knowledge and gave books and other learning tools to them.
    
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Fluent
  programmingSkills:
    - skill1:
      name: C/C++
      percentage: 40%
    - skill2:
      name: LaTex
      percentage: 30%
    - skill3:
      name: Matlab
      percentage: 40%
